# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: li2go
email: admin@diaofly.com
description: just simple blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://diaofly.com" # the base hostname & protocol for your site
twitter_username: li2go
github_username:  li2go
post_title: Articles
comments:
  provider: duoshuo
  duoshuo:
    short_name: diaofly
# Build settings
markdown: kramdown

#own verbs

